services:
  app:
    ports:
      - "18130:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://herokku.duckdns.org:18130}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - OAUTH_GITHUB_ID=${OAUTH_GITHUB_ID}
      - OAUTH_GITHUB_SECRET=${OAUTH_GITHUB_SECRET}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ENCRYPTION_IV=${ENCRYPTION_IV}
      - CRON_SECRET_TOKEN=${CRON_SECRET_TOKEN}
      - BLOB_READ_WRITE_TOKEN=${BLOB_READ_WRITE_TOKEN:-}
    volumes:
      - uploads_data:/app/public/uploads
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  db:
    ports: []
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  uploads_data:
    name: portafolios_uploads_data
    driver: local
