services:
  app:
    ports:
      - "8130:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://herokku.duckdns.org:8130}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - OAUTH_GITHUB_ID=${OAUTH_GITHUB_ID}
      - OAUTH_GITHUB_SECRET=${OAUTH_GITHUB_SECRET}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes: []
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  
  db:
    ports: []
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
