services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"   # HTTP en puerto 8080 (evita conflictos)
      - "8443:443"  # HTTPS en puerto 8443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  app:
    ports: []
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://herokku.duckdns.org
    networks:
      - app-network

  db:
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
